version: "3.9"

services:
  node-red:
    build: ./docker-node-red
    container_name: nrwm-node-red
    ports:
      - "1880:1880"
    volumes:
      - ./docker-node-red/data:/data
    command: npm start -- --userDir /data
    environment:
      - TZ=America/New_York
    depends_on:
      - mariadb
    restart: "no"

  mariadb:
    image: mariadb:10.5.12
    container_name: nrwm-mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: ""
      MYSQL_DATABASE: process
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    restart: "no"
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nrwm-phpmyadmin
    restart: "no"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - "8080:80"